### ISSUE TITLE
[PW-2598] Exclude / include products for a specific payment method

### ISSUE THREAD

**Issue by stm2roi3** [Adyen/adyen-shopware5#10]
**Is your feature request related to a problem? Please describe.**
Within our shop we can not select or de-select product specific payment methods and cannot deactivate payment methods by ourself. This is especially relevant for e.g. bookings as we need a valid response for the payment receipt within 15 minutes. In consequence we need to deactivate a payment method (e.g. Klarna directEbanking) globally for bookings, but as a consequence customers cannot use the payment method for not time-critical orders.  

**Describe the solution you'd like**
Show adyen payment under the settings -> payment methods tab in shopware to use the native shopware functionality

**Describe alternatives you've considered**
Selector within the plugin to connect products or categories to a payment method or to exclude product or categories for a payment method

**Comment by Suzell** [comment]
Will be resolved with #152
