### ISSUE TITLE
Test API button only uses first shop data

### ISSUE THREAD

**Issue by acampos1916** [Adyen/adyen-shopware5#100]
**Describe the bug**
When testing the API connection the data used is always coming from the first tab/shop.

**To Reproduce**
1. Set up multiple stores.
2. Go to the plugin admin panel.
3. Set wrong API data for the first store and correct data for the second store.
4. Click on "Test API connection" with the second tab active.
5. The connection test fails.

**Expected behavior**
The data tested should come from the active tab.

**Comment by wannevancamp** [comment]
@acampos1916 , we discussed this with Shopware. It's technically not possible to receive the shop of the selected tab in the backend. Because of that we can't determine the correct shop for the Test API button.
It's a limitation of Shopware 5

**Comment by acampos1916** [comment]
Parking this issue for now as it doesn't have a clear workaround
