### ISSUE TITLE
Show Adyen General Payment Method in the backend

### ISSUE THREAD

**Issue by acampos1916** [Adyen/adyen-shopware5#104]
**Is your feature request related to a problem? Please describe.**
The admin panel does not show the Adyen payment method. But could it be shown to modify how ALL Adyen PMs behave?

**Describe the solution you'd like**
Show the Adyen General Payment Method in the backend so it's configuration affects all Adyen PMs.

**Comment by Suzell** [comment]
will be resolved with #152
