### ISSUE TITLE
[PW-2723] Incorrect locale taken in the checkout

### ISSUE THREAD

**Issue by floorjubbega** [Adyen/adyen-shopware5#11]
**Describe the bug**
The incorrect locale is taken for shoppers within the checkout. From a German IP selecting a German delivery or billing address the locale sent in the payments request is still en_GB.
This is causing the shopper to see incorrect language locales in their checkout (for example the language for Klarna)

**To Reproduce**
1. Checkout while selecting location delivery/billing address Germany
2. IP is also in Germany
3. In request we see en_GB
4. Klarna checkout shows up in English

**Expected behavior**
Klarna checkout should show up in German for German IP/billing address.

**Comment by runelaenen** [comment]
The locale is not generated by IP or address, but based on the language of your shop.  So if your storeview has English, then English will be passed as locale.

https://github.com/Adyen/adyen-shopware5/blob/develop/Components/Payload/Providers/ShopperInfoProvider.php#L28

**Comment by acampos1916** [comment]
Merchant that reported this issue updated the plugin to a newer version and this problem is no longer present.
