### ISSUE TITLE
Adyen payment details are not returned from Shopware REST API

### ISSUE THREAD

**Issue by ataberkylmz** [Adyen/adyen-shopware5#119]
**Is your feature request related to a problem? Please describe.**
If you make an /api/orders request (via Shopware's [REST API](https://developers.shopware.com/developers-guide/rest-api/)), no details returned about the Adyen payment (most importantly no PSP reference). Please find the partial body from attempts:

```
"payment": {
    "id": 8,
    "name": "adyen_general_payment_method",
    "description": "Adyen payment methods",
    "template": "",
    "class": "",
    "table": "",
    "hide": false,
    "additionalDescription": "",
    "debitPercent": 0,
    "surcharge": 0,
    "surchargeString": "",
    "position": 0,
    "active": true,
    "esdActive": false,
    "mobileInactive": false,
    "embedIFrame": "",
    "hideProspect": 0,
    "action": null,
    "pluginId": null,
    "source": null,
    "attribute": null
},
```
Maybe it is best to add details of the payment into the "payment" key, or at least populate the "additionalDescription" with the PSP reference from the payment.

**Comment by olga-adyen** [comment]
Added to roadmap
