### ISSUE TITLE
Order confirmation mails are sent regardless of success

### ISSUE THREAD

**Issue by floorjubbega** [Adyen/adyen-shopware5#12]
**Describe the bug**
Even if the order fails, the Shopware plugin still sends a confirmation mail to the shopper and the orders are still set to open within Shopware. This can be very confusing as both the shopper and the merchant are unsure if the transaction was completed. We need to cancel the order within Shopware if an authorisation notification comes in with success = false.

Examples of when order confirmation is sent:

- Amex/Visa card blocked, still a confirmation mail
- 3DS unsuccessful, still a confirmation mail.
- CVC declined, still a confirmation mail

**To Reproduce**
1. Checkout with a card transaction
2. Input the wrong cvc
3. Still receive an order confirmation through mail
4. Redirect to the checkout page with empty cart

**Expected behavior**
Expected behavior would be to have no order confirmation, and the cart remains with the items to allow for a second transaction attempt.

**Comment by runelaenen** [comment]
Hi @floorjubbega 
I have tested this but do get the correct flow. I think this is the same issue as in #16 
Is it possible to provide log files from the times these customers have been redirected incorrectly?

Thanks.

Screenrecording: [_screenrecording_github_adyen_1.mov.zip](https://github.com/Adyen/adyen-shopware5/files/5102648/_screenrecording_github_adyen_1.mov.zip)
I've first tested it with CC number 4242 4242 4242 4242 but a wrong cvc. 2nd time I test with a faulty CC number. Both times it redirects to the checkout again, with the cart correctly remembered, temporary order cancelled, and no e-mail sent.

**Comment by danielDigitalArt** [comment]
Hi @runelaenen,

i tried this out. Maybe it is easier to test this with a different Payment Method. I used Ideal Payment, where i get to a different screen to select some settings. The moment that i leave the shop page i already get the order confirmation e-mail.

Please make sure while testing, that your system would actually send order confirmation mails to you, otherwise it obviously can not happen.

**Comment by Hoffmannsvenja** [comment]
Hello Rune,
I've tested it again in our live environment. I used my credit card but a wrong expiry date. 
![image](https://user-images.githubusercontent.com/70256621/91269919-29b45f80-e778-11ea-8be9-4219f4b59cf8.png)
 The shop transferred me back the the chechout: **Your transaction was refused by the Payment Service Provider.**
An Email was sent: 
![image](https://user-images.githubusercontent.com/70256621/91271134-0094ce80-e77a-11ea-82c9-034993283f2b.png)
I did not receive a log in the backend from Shopware
![image](https://user-images.githubusercontent.com/70256621/91271560-ac3e1e80-e77a-11ea-8f45-dd37bc0482d9.png)
I have a log in the console output:
![image](https://user-images.githubusercontent.com/70256621/91272904-c547cf00-e77c-11ea-9caa-d89649ad8e85.png)

cb1
1598426067_5fa43ea15fa82cd0146a62bcd30e7510.js:777 cb2
www.google-analytics.com/analytics.js:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
1598426067_5fa43ea15fa82cd0146a62bcd30e7510.js:808 !$(".full").length>0-1
1598426067_5fa43ea15fa82cd0146a62bcd30e7510.js:808 k.fn.init(0)
1598426067_5fa43ea15fa82cd0146a62bcd30e7510.js:808 changed position to: 181.22222900390625
checkout:1 A cookie associated with a cross-site resource at https://adyen.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
checkout:1 A cookie associated with a cross-site resource at http://adyen.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Does that help?

**Comment by danielDigitalArt** [comment]
Hi,

we still have this Problem with the official released Version from the Shoppware Store, we are running it on a fresh install with Shopware 5.6.8 without any other plugins installed.
