### ISSUE TITLE
Wrong Order Details, when the order has an error

### ISSUE THREAD

**Issue by danielDigitalArt** [Adyen/adyen-shopware5#121]
**Describe the bug**
When an order is made, sometimes the shop does not process the transaction further, we only see a loading animation. When this happens we see that the function "ajaxDoPayment" results in an error where the OrderID creates a mysql-error. When this happens the Customer-Data is altered by adyen. The username and also his addresses are completely different, it seems as there were different data loaded from another shop-system or Adyen customer. If this is true and these data are not some kind of random Userdata or testdata, this will also be a security issue, as i now have the customer data of someone elses shop-system.

**Expected behavior**
The order gets processed without an error and the customer data is not altered.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 88

**Additional context**
Shopversion: 5.6.9
Pluginversion: 1.6.0 (from Shopware Store)
Plugin is running in Test-Mode.

**Error Message:**

> <h2>Oeps! Er is een fout opgetreden!</h2> <p> De hiernavolgende informatie helpt u wellicht verder. </p> <h3>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;701&#039; for key &#039;orderID&#039; in engine/Library/Zend/Db/Statement/Pdo.php on line 224</h3> <h3>Stack trace:</h3> <div style="overflow:auto;"> <pre>#0 engine/Library/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo-&gt;_execute(Array)
> #1 engine/Library/Zend/Db/Adapter/Abstract.php(472): Zend_Db_Statement-&gt;execute(Array)
> #2 engine/Library/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract-&gt;query(&#039;\n        INSERT...&#039;, Array)
> #3 engine/Library/Enlight/Components/Db/Adapter/Pdo/Mysql.php(83): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;\n        INSERT...&#039;, Array)
> #4 engine/Library/Enlight/Components/Db/Adapter/Pdo/Mysql.php(98): Enlight_Components_Db_Adapter_Pdo_Mysql-&gt;query(&#039;\n        INSERT...&#039;, Array)
> #5 engine/Shopware/Core/sOrder.php(1095): Enlight_Components_Db_Adapter_Pdo_Mysql-&gt;executeUpdate(&#039;\n        INSERT...&#039;, Array)
> #6 engine/Shopware/Core/sOrder.php(807): sOrder-&gt;sSaveBillingAddress(Array, &#039;701&#039;)
> #7 engine/Shopware/Controllers/Frontend/Payment.php(113): sOrder-&gt;sSaveOrder()
> #8 custom/plugins/AdyenPayment/Controllers/Frontend/Adyen.php(221): Shopware_Controllers_Frontend_Payment-&gt;saveOrder(33, &#039;dd8ec360322e467...&#039;, 17, false)
> #9 custom/plugins/AdyenPayment/Controllers/Frontend/Adyen.php(169): Shopware_Controllers_Frontend_Adyen-&gt;prepareOrder(Object(AdyenPayment\Models\PaymentInfo))
> #10 custom/plugins/AdyenPayment/Controllers/Frontend/Adyen.php(73): Shopware_Controllers_Frontend_Adyen-&gt;createPaymentContext()
> #11 engine/Library/Enlight/Controller/Action.php(192): Shopware_Controllers_Frontend_Adyen-&gt;ajaxDoPaymentAction()
> #12 engine/Library/Enlight/Controller/Dispatcher/Default.php(478): Enlight_Controller_Action-&gt;dispatch(&#039;ajaxDoPaymentAc...&#039;)
> #13 engine/Library/Enlight/Controller/Front.php(228): Enlight_Controller_Dispatcher_Default-&gt;dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
> #14 engine/Shopware/Kernel.php(188): Enlight_Controller_Front-&gt;dispatch()
> #15 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(102): Shopware\Kernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #16 vendor/symfony/http-kernel/HttpCache/HttpCache.php(453): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle(Object(Shopware\Kernel), Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #17 engine/Shopware/Components/HttpCache/AppCache.php(261): Symfony\Component\HttpKernel\HttpCache\HttpCache-&gt;forward(Object(Symfony\Component\HttpFoundation\Request), true, NULL)
> #18 vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Shopware\Components\HttpCache\AppCache-&gt;forward(Object(Symfony\Component\HttpFoundation\Request), true)
> #19 vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache-&gt;pass(Object(Symfony\Component\HttpFoundation\Request), true)
> #20 engine/Shopware/Components/HttpCache/AppCache.php(143): Symfony\Component\HttpKernel\HttpCache\HttpCache-&gt;invalidate(Object(Symfony\Component\HttpFoundation\Request), true)
> #21 vendor/symfony/http-kernel/HttpCache/HttpCache.php(181): Shopware\Components\HttpCache\AppCache-&gt;invalidate(Object(Symfony\Component\HttpFoundation\Request), true)
> #22 engine/Shopware/Components/HttpCache/AppCache.php(113): Symfony\Component\HttpKernel\HttpCache\HttpCache-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #23 shopware.php(122): Shopware\Components\HttpCache\AppCache-&gt;handle(Object(Symfony\Component\HttpFoundation\Request))
> #24 {main}</pre> </div>

**Comment by acampos1916** [comment]
Hello @danielDigitalArt, thanks for opening this issue.

It is a very strange behavior indeed. Could you provide some detailed steps to try to reproduce?

Thanks,
Ángel

**Comment by danielDigitalArt** [comment]
Sadly not really, all what happens is that i get an error when i try to get to the Payment Page of the selected Adyen Payment, i had this with multiple (ideal) Payments like Test Issuer 5 etc.

I dont get to the proper Payment page as the Shop is stuck with that loading animation in the frontend, while showing the added error in the browsers console.

So i can select i.e. Idead ° Test Issuer 5 as payment method, then i want to go to the last step, where i get redirected to the adyen payment page, but before getting there the error happens.

**Comment by danielDigitalArt** [comment]
@acampos1916 i think i could rule out the problem here now. The hint was the duplicate entry, there were some Data from Testings and i guess from imports, the data was in the order_billingaddress and was then added to the current orderid. I do not really know why the orderid was reset, but it explains Userdata appearing out of nowhere. So i tested after cleaning the Tables and could not yet see this particular Problem again, also the duplicate error Message in general should be gone away too now.
