### ISSUE TITLE
Managing customer account > preferred payment methods won't work

### ISSUE THREAD

**Issue by jensorben** [Adyen/adyen-shopware5#128]
With the new feature of saving payment methods data the user is no longer able to edit or change his preferred payment method or payment data on his shopware buyers account.
The input array seems to be missconfigured. As a result, the payment method configuration page is nearly left blank with two non-signed option buttons. Also other payment methods outside adyen system (e.g. cash on delivery, advance payment as well as origin paypal-plugin) weren't shown.
![#2-PaymentMethodsOnAccount](https://user-images.githubusercontent.com/69344793/106635572-4b184380-6581-11eb-995e-9815be5c3ced.jpg)
A screenshot is given. It showas the page of  ../en/account/payment

**Comment by acampos1916** [comment]
Hello @jensorben, thanks for opening this issue.

@bortefi I see that your PR #127 seems to address some issues with stored payment methods. Do you think that by any chance this also related?

**Comment by bortefi** [comment]
@acampos1916  This issue is indeed related,the pull request resolves this issue.

**Comment by acampos1916** [comment]
Thanks @bortefi!

@jensorben we'll be reviewing and merging #127 soon, but feel free to test that branch/PR beforehand to verify that the issue is solved for you.

**Comment by jensorben** [comment]
@acampos1916 Thanks for your information but we were not allowed to test branches.
