### ISSUE TITLE
[PW-4379] User Comments missing

### ISSUE THREAD

**Issue by danielDigitalArt** [Adyen/adyen-shopware5#129]
**Describe the bug**
When i was testing the plugin, i added a Comment to every Order so i know what i was testing there, The Orders were done properly but in the backend i do not see the comment symbol, and there are also no contents in the comment section in the backend.

**To Reproduce**
1. Go to Checkout
2. Add a Comment
3. Proceed with a Adyen Payment selected
4. Finish the Payment Process
5. Finish the Order
6. Go into the Backend
7. Look into Orders

**Expected behavior**
Comments should be available in the Order-List/Order-Detail

**Note**
Normal Payment Methods and other Payment-Provider Plugins were able to set the info into the Order-Details, so it can not be a general problem of the shop. No Other Payment Provider Plugin was active when i tested the adyen payment, i just switched the plugin when i was done with them.

**Update 1.7.1:**
The Problem is still persistent

**Comment by peterojo** [comment]
Hello @danielDigitalArt, I don't see a way to add comments in Checkout and our plugin does not provide this feature, are you perhaps using another plugin for this?

**Comment by danielDigitalArt** [comment]
@peterojo 
No Plugin is needed, it is just hidden behind another setting in the basic-settings of the shop:
![Bildschirmfoto 2021-04-26 um 16 44 31](https://user-images.githubusercontent.com/25100967/116102286-e1569400-a6ae-11eb-950f-53d1f03e945a.png)
After setting this field to "yes" and clearing all caches, you should see this in the last checkout page:
![Bildschirmfoto 2021-04-26 um 16 44 06](https://user-images.githubusercontent.com/25100967/116102519-106d0580-a6af-11eb-812a-477a9ad4524c.png)
