### ISSUE TITLE
Shipping Methods are not displayed anymore

### ISSUE THREAD

**Issue by Gugiman** [Adyen/adyen-shopware5#133]
**Describe the bug**
Considering this:
https://github.com/Adyen/adyen-shopware5/blob/1.7.0/Subscriber/PaymentSubscriber.php#L114

After altering the structur of the return of the sGetPaymentMeans() method, some functions are not working anymore.

- No shipping methodes can be selected on the confirm page. I think Shopware is not able to determine which method is valid.
- Also on change payment on account page. There is no payment selectable. I think it's because changes in the structure are not handled in account page. (But in change_payment.tpl on checkout)

**To Reproduce**
- Try to change shipping method which may be restricted by paymeant means.
- Try to change payment on account page.

**Expected behavior**
Change payment and shipping on every page where it is a default function.

**Screenshots**
checkout/shippingPayment/sTarget/checkout
![image](https://user-images.githubusercontent.com/5836639/107235530-0d099c80-6a25-11eb-86b7-91ddb534470b.png)

account/payment
![image](https://user-images.githubusercontent.com/5836639/107236398-f7e13d80-6a25-11eb-98e6-7abed2ee2591.png)

Shopware 5.6.9
Plugin Version 1.7.0

**Comment by acampos1916** [comment]
Hello @Gugiman, can you confirm if this is a duplicate of #126? If so then you can verify if #131 fixes the issue.

**Comment by Gugiman** [comment]
Hi @acampos1916 
I can confirm all of this :)

Therefore closed!

Thank you!
