### ISSUE TITLE
[PW-4128] Payment Method Headline is shown twice in Payment Selection

### ISSUE THREAD

**Issue by danielDigitalArt** [Adyen/adyen-shopware5#135]
**Describe the bug**
With Version 1.7.1 from the Store the Payment Methods Headline is shown twice (here in two differen languages) on is coming from the System and one is coming from Adyen. I created a Screenshot from the normal View and also from the source code.

**Expected behavior**
Only the correct translation is shown by the shop (as it was in the old release)

**Screenshots**
![Bildschirmfoto 2021-02-10 um 11 35 28](https://user-images.githubusercontent.com/25100967/107499186-eff3db80-6b94-11eb-9da2-77c0bc43b5df.png)
![Bildschirmfoto 2021-02-10 um 11 39 07](https://user-images.githubusercontent.com/25100967/107499219-f8e4ad00-6b94-11eb-96b3-2936f9cc344d.png)

**Additional context**
I already tried to save the Plugin config after updating in the Shopware backend. I then saw that the Problem is still there and thus clicke on "re-install" and then cleared the cache (including theme compilinig). Problem still persists.

**Comment by acampos1916** [comment]
Hello @danielDigitalArt,

Indeed the plugin will list the methods in two groups:

Betaalwijze wijzigen (Shopware title).
 - Payment methods (Adyen title, translatable).
 - Stored payment methods (Adyen title, translatable).

Both "Payment methods" and "Stored payment methods" are Snippets that can be translated in the Shopware admin.

In [this PR](https://github.com/Adyen/adyen-shopware5/pull/138) the titles are being hidden if only one group is present, also an indentation is introduced to differentiate the sections.

Thanks,
Ángel
