### ISSUE TITLE
Hide Adyen payment methods for 0 amount transactions.

### ISSUE THREAD

**Issue by ataberkylmz** [Adyen/adyen-shopware5#139]
**Describe the bug**
Credit cards and PayPal payment methods are returned from a zero amount transaction and Adyen payment methods should be hidded in this case even though we get them back in the response. Ideally, there should be toggle to enable and disable this feature as you can make zero value authentications with credit cards to tokenize the payment methods.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by peterojo** [comment]
We seem to be unable to get the total amount of the basket from the session [here](https://github.com/Adyen/adyen-shopware5/blob/06bcf4c5f87d65f2a1dd58724a4d5b0c8f898709/Components/PaymentMethodService.php#L222) @bortefi do you have an idea how we can use the total amount to filter out all Adyen PMs?

**Comment by bortefi** [comment]
Hi @peterojo 

To not use the session it's best to use the sBasket service: \sBasket::sGetAmount();
Keep in mind this also does use the sessionId to fetch the correct basket.

Basket service is available through global Shopware function:
`Shopware()->Modules()->Basket();`
or with DI expression:
`<argument type="expression">container.get('modules').Basket()</argument>`
