### ISSUE TITLE
DB grows fast because of inefficient db structure

### ISSUE THREAD

**Issue by wannevancamp** [Adyen/adyen-shopware5#147]
**Describe the bug**
In #46 a new db field ordermail_variablesin in s_plugin_adyen_order_payment_info is introduced and released 1.5.1. A lot of unnecessary data is saved in the db which causes a big table which has impact on the performance. 

**To Reproduce**
1. place ~100000 orders
2. check db size of table s_plugin_adyen_order_payment_info
3. size > 2GB

**Expected behavior**
2 possible options:
1. dynamically retrieve order information
2. only save needed order information

**Comment by bortefi** [comment]
@acampos1916 mail variables are only available during the creation process of Shopware 5

An alternative solution could be to clear the order variables from s_plugin_adyen_order_payment_info,
when the e-mail is sent.

**Comment by acampos1916** [comment]
Thanks @wannevancamp @bortefi I can see how this could lead to a huge database.

I like the idea of dynamically getting the variables when needed. Any pointers on how to do that?

We could also clear the data from the table when the email is sent but the above should be leaner.

**Comment by bortefi** [comment]
Shopware will create the mail variables during saving of the order: `\sOrder::sSaveOrder`
these variables are used in
* `\sOrder::sendMail` 
* `\AdyenPayment\Subscriber\OrderEmailSubscriber`
* `\AdyenPayment\Components\OrderMailService`
* Since they are only stored in a session variable a custom `OrderMailVariableCollector` or other `sevice` is best created to obtain the data like sOrder does during save.

Context of sOrderSave:
```
...
\sOrder::sSaveOrder
...
 $variables = [
            'sOrderDetails' => $details,
            'billingaddress' => $this->sUserData['billingaddress'],
            'shippingaddress' => $this->sUserData['shippingaddress'],
            'additional' => $this->sUserData['additional'],
            'sShippingCosts' => $this->sSYSTEM->sMODULES['sArticles']->sFormatPrice($this->sShippingcosts) . ' ' . $this->sBasketData['sCurrencyName'],
            'sAmount' => $this->sAmountWithTax ? $this->sSYSTEM->sMODULES['sArticles']->sFormatPrice($this->sAmountWithTax) . ' ' . $this->sBasketData['sCurrencyName'] : $this->sSYSTEM->sMODULES['sArticles']->sFormatPrice($this->sAmount) . ' ' . $this->sBasketData['sCurrencyName'],
            'sAmountNumeric' => $this->sAmountWithTax ? $this->sAmountWithTax : $this->sAmount,
            'sAmountNet' => $this->sSYSTEM->sMODULES['sArticles']->sFormatPrice($this->sBasketData['AmountNetNumeric']) . ' ' . $this->sBasketData['sCurrencyName'],
            'sAmountNetNumeric' => $this->sBasketData['AmountNetNumeric'],
            'sTaxRates' => $this->sBasketData['sTaxRates'],
            'ordernumber' => $orderNumber,
            'sOrderDay' => date('d.m.Y'),
            'sOrderTime' => date('H:i'),
            'sComment' => $this->sComment,
            'attributes' => $attributes,
            'sEsd' => $esdOrder,
        ];
...
$this->sendMail($variables);

```

**Comment by olga-adyen** [comment]
Added to roadmap, will close.
