### ISSUE TITLE
No payment but redirect to /checkout/finish

### ISSUE THREAD

**Issue by Gugiman** [Adyen/adyen-shopware5#157]
Hi,

sometimes users are redirected to the /checkout/finish page but there is no payment screen for e.g. PayPal. 

**FIrst guess**
When opening the cart the URL ist called:
/checkout/confirm

When changing shipping/payment method it is called:
/checkout

I saw some conditions in CheckoutSubscriber.php which looks for the action name "confirm". Might be a problem but i am not quite sure.

**Important new information:**
We figured out that this problem seems to occur (and is reproducible) only by using Internet Explorer.
In our case Version 11.
access_log from our server confirms this cause by looking at the user-agent.
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`

Maybe there is some sort auf JS race condition because the ajax call "ajaxDoPayment" gets stuck as you see on the network tab of the "developer-Tools"

**Comment by peterojo** [comment]
Hi @Gugiman, I was not able to reproduce this issue at the moment, could you please try it with the latest release 1.7.2?
