### ISSUE TITLE
[PW-4355] "Test credentials" not working

### ISSUE THREAD

**Issue by StephanAltmann85** [Adyen/adyen-shopware5#162]
**Describe the bug**
Error message: Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "shop".

**To Reproduce**
1. go to plugin manager and edit configuration of Adyen plugin
2. click on test credentials

**Screenshots**
![test-crdentials](https://user-images.githubusercontent.com/7197443/115122427-33fdc500-9fb8-11eb-9863-016335628680.png)

**Desktop (please complete the following information):**
Shopware 5.6.9
Adyen 1.7.1

**Comment by StephanAltmann85** [comment]
Reason: 
`$paymentMethodService = $this->get('adyen_payment.components.adyen.payment.method');`

`<argument type="service" id="session"/>` This service is not available in the backend.

**Comment by acampos1916** [comment]
Thanks for opening this issue @StephanAltmann85. This test function is being refactored in #155 and that service won't be used anymore.
