### ISSUE TITLE
Credit Card wrong checkout finish

### ISSUE THREAD

**Issue by reConNico** [Adyen/adyen-shopware5#163]
**Describe the bug**
When credit card is used the order goes through and is correct in the backend and in adyen as well. Backend wise everything is working. Sadly the frontend isn't working as expected because the customer get's redirected to the checkout changePayment page instead of the checkout finish page. The url is correct: `/checkout/finish/` but the view is wrong. Because the order goes through the cart is empty.

**To Reproduce**
1. Go to https://update.livario.com
2. Choose a product and go to the payment selection page in the checkout process
3. Choose "Kreditkarte" at the top
4. Finish the order
5. See error the wrong view (the correct finish page is not displayed)

**Expected behavior**
The correct finish page should be shown.

**Screenshots**
![Screenshot from 2021-04-20 11-31-37](https://user-images.githubusercontent.com/15830979/115374640-53217000-a1cd-11eb-9156-17cf938dc195.png)

**Additional Informations**
Test cards: https://docs.adyen.com/development-resources/test-cards/test-card-numbers

**Comment by acampos1916** [comment]
Hey @reConNico thanks for opening this issue.

Which version of the plugin and Shopware 5 are you using? We can try to reproduce this.

**Comment by reConNico** [comment]
Hey @acampos1916 ,

Shopware v5.6.8 is in use.

**Comment by reConNico** [comment]
Short update from my side @acampos1916 :

I've found out what the problem is and it seems like that it's a project specific problem or a third party plugin. 

The `finishAction` in `Shopware_Controllers_Frontend_Checkout` runs into the second if condition because the `sDispatch` in the session is null and that's why Shopware is redirecting to the `checkout/confirm` page without a dispatch selected. The order goies through.

I'll update this issue again when I've new informations.

**Comment by acampos1916** [comment]
Thanks for the update @reConNico. Indeed if this isn't reproducible in a clean Shopware installation then it could be a different plugin. Let us know of your findings.

**Comment by cyattilakiss** [comment]
Hi @reConNico 

I hope you had a nice weekend!
Do you have any update for us regarding this issue?

Best,
Attila
Adyen

**Comment by acampos1916** [comment]
@reConNico we'll be closing the issue now due to inactivity but let us know if you have an update.
