### ISSUE TITLE
Error when Adyen payment is default payment

### ISSUE THREAD

**Issue by forty-four** [Adyen/adyen-shopware5#164]
When Adyen is set as default payment method, newly registered customers will get an error at checkout:
![image](https://user-images.githubusercontent.com/7996627/116062051-d63a3e80-a683-11eb-91fe-09f78001a95b.png)

That's because the value of s_user_attributes.adyen_payment_payment_method will be NULL, but fetchByTypeOrId($selectedType) in the method shouldRedirectToStep2() (Subscriber/CheckoutSubscriber.php) only accepts type of String (Collection/Payment/PaymentMethodCollection.php):
public function fetchByTypeOrId(string $paymentTypeOrId)

**Comment by forty-four** [comment]
Added a quick and dirty fix:
![image](https://user-images.githubusercontent.com/7996627/116064435-4cd83b80-a686-11eb-8f85-71422ec357a7.png)
Maybe it's better to set an empty string as default value of s_user_attributes.adyen_payment_payment_method

**Comment by acampos1916** [comment]
Thanks for opening this issue @forty-four.

I believe this was already addressed in #132 which is being released in 1.7.2 #156. Since this is already merged I'll close this now but feel free to add more info.
