### ISSUE TITLE
[PW-5048] Problem with credit card payment and 3D Secure 2 authentication

### ISSUE THREAD

**Issue by andydandy80** [Adyen/adyen-shopware5#173]
Shopware: 5.6.10
Adyen-Plugin: 2.0.0

Our Shop is running in a test environment and under a sub directory of a domain => e.g.: "https://myshop.de/test/..."

When you use credit card and a test number with 3d secure auth the order finish button is not working, due to a buggy ajax call to function "ajaxThreeDs". We got 404 not found in browser console.

File:
.../custom/plugins/AdyenPayment/Resources/frontend/js/jquery.adyen-confirm-order.js"
Lines 15 + 16
            adyenAjaxDoPaymentUrl: '/frontend/adyen/ajaxDoPayment',
            adyenAjaxThreeDsUrl: '/frontend/adyen/ajaxThreeDs',

The urls are hardcoded and do not mention our sub directory.

I have changed it manually, now its working.

**Comment by acampos1916** [comment]
Thanks for opening this issue @andydandy80, seems like the plugin should include the shop's full path in those URL variables. I've opened an internal ticket to look into it.

**Comment by Suzell** [comment]
The hardcoded url has been replaced by a generated one (which includes the sub folder). This is be resolved after new major release #176. Thanks!
