### ISSUE TITLE
Compatibility for Shopware's "Subscriptions - Commerce"-plugin

### ISSUE THREAD

**Issue by magnolia4** [Adyen/adyen-shopware5#174]
We are currently still using the payment plugin from customweb / sellxed because our customer can offer recurring payments via this plugin.

So that we can use the adyen plugin, compatibility with the Shopware plugin "Subscriptions - Commerce" must be guaranteed https://store.shopware.com/en/swagabocommerce/subscriptions-commerce.html which our customer uses for recurring payments.

**Comment by Suzell** [comment]
I am closing this ticket as after investigating this plugin it is not an easy plugin to become compatible with as there are a lot of complexities in the code. Therefore we will not be supporting it at the moment and if any more requests we can revisit it with Shopware.
