### ISSUE TITLE
[PW-5181] Minimum order value is not processed correctly

### ISSUE THREAD

**Issue by anothaNj** [Adyen/adyen-shopware5#177]
When the order is placed with a test credit card a warning that the minimum order value is not reached is shown. The order is not placed and the cart is empty. 

**Steps to reproduce the behavior:**
1. Configure the minimum order value for 20euros in Shopware basis settings
2. Add products to reach over minimum order value
3. Start the checkout
4. Payment with Adyen test credit card
5. Submit order
6. Error is shown

**Expected:**
The warning should only be shown if the minimum order value is not reached. If it is reached the order should be normally processed.

![MindestbestellwertStattBestätigung](https://user-images.githubusercontent.com/26765837/126598888-e35ea59f-219a-407e-b2a2-a6d4a9b68270.png)

 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.124
 - Shopware 5.6.6
 - Adyen Plugin 2.0.0

**Additional info:**
Minimum order value is 20€, actual order value is 30€

**Comment by cyborgii** [comment]
Please find attached a screenshot how to configure this feature
![22-07-_2021_12-58-51](https://user-images.githubusercontent.com/247184/126629403-98133a00-424b-4f25-9f05-b5be695639dc.png)

**Comment by acampos1916** [comment]
Thanks for this report @anothaNj @cyborgii. We've opened an internal ticket to investigate this and come up with a solution.

**Comment by acampos1916** [comment]
Adding more info to this issue: This seems to be caused by a session mismatch. When the order minimum amount is set the `sCheckMinimumCharge` function will call `sGetAmount` which will try to use the sessionId to fetch the basket data, but the sessionId does not match the rows in s_order_basket.

**Comment by acampos1916** [comment]
Hello @anothaNj, could you confirm if #184 solves this issue for you?
