### ISSUE TITLE
Support manual capture from the plugin

### ISSUE THREAD

**Issue by Suzell** [Adyen/adyen-shopware5#181]
**Is your feature request related to a problem? Please describe.**

Right now the plugin only supports immediate capture. If a merchant wants to capture on shipment then need to send a manual capture request from Shopware.

**Comment by bortefi** [comment]
Hi Suzanne, 
Is this ticket is it about: https://docs.adyen.com/online-payments/capture#manual-capture?

Could you elaborate a bit more about how this should be working with the plugin?
How / when the capture will take place, this can only take happen after an order has been placed and an PSP reference is available?

(internal reference: ASW-333)

**Comment by olga-adyen** [comment]
Added to the roadmap, will close issue.
