### ISSUE TITLE
Confirm page shows error before payment method has been selected

### ISSUE THREAD

**Issue by peterojo** [Adyen/adyen-shopware5#185]
**Describe the bug**

When proceeding to checkout for the first time, [`shouldRedirectToStep2`](https://github.com/bortefi/adyen-shopware5/blob/b107b2e2926033ac3db2322d7d73fe36640df07a/Subscriber/CheckoutSubscriber.php#L161) returns false and user is redirected directly to the confirm page.
Since the payment config is not yet set in the component, the following error is shown on the checkout page:
```
Your transaction was cancelled due to an unknown reason. Please make sure your browser allows cookies.
```

**To Reproduce**
1. Proceed to checkout as guest user
2. See error

**Expected behavior**
New user should be redirected to the page for selecting payment

**Screenshots**
![Screen Shot 2021-09-24 at 3 56 46 PM](https://user-images.githubusercontent.com/5240725/134689466-ff087f6f-3426-435f-80d0-79a4cf953cfb.png)
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Google Chrome

**Comment by Suzell** [comment]
Resolved with release 3.2.0
