### ISSUE TITLE
fatal error with new version 3.0.0

### ISSUE THREAD

**Issue by magnolia4** [Adyen/adyen-shopware5#187]
Shopware: 5.6.8
PHP: 7.3.29
Adyen 3.0.0

When we install the 3.0.0 update, we get a fatal error:

`Fatal error: Declaration of Shopware\Components\Log\Handler\ChromePhpHandler::sendHeader($header, $content) must be compatible with Monolog\Handler\ChromePHPHandler::sendHeader(string $header, string $content): void in /engine/Shopware/Components/Log/Handler/ChromePhpHandler.php on line 34`

**Comment by webtech-tom** [comment]
Same error

Shopware: 5.6.10
PHP: 7.3.29
Adyen 3.0.0

Right after clicking on update.

**Comment by acampos1916** [comment]
Thanks for the suggestion @ifbidev, indeed this is a problem with the package zip file and we're updating it soon. @webtech-tom be aware that after deleting the contents of the package and cloning the master branch you also need to install the package's dependencies https://docs.adyen.com/plugins/shopware-5/?tab=git_hub_3
