### ISSUE TITLE
Adyen payment methods blocks rendering other payment methods

### ISSUE THREAD

**Issue by Suzell** [Adyen/adyen-shopware5#189]
**Describe the bug**
Once our plugin is enabled and the individual payment methods are imported, our payment methods block the rendering of other payment methods (such as PayPal's own plugin, Invoice, Cash, etc) on Shopware 5 v3.0.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/68321084/136788282-9ea564e4-c16b-4370-97f5-663f809a7521.png)
![Screen Shot 2021-10-11 at 1 51 59 PM](https://user-images.githubusercontent.com/68321084/136788378-fc545173-00e5-4098-a014-136c52d7343d.png)

**Comment by reConNico** [comment]
@bortefi : There is no real documentation on this fix in the `3.1.0` release. The problem we have: We can't upgrade to that version because we're running on Shopware 5.6.8 right now and the `3.1.0` version doesn't work with our shopware version.

Can you provide a release `3.0.3` with this fix or provide the correct changes that has to be made?

**Comment by bortefi** [comment]
Hello @reConNico 

Providing a 3.0.3 release won't be possible, as focus of the plugin development is keeping it it up to date with latest Shopware 5 versions (currently 5.7.x).
Shopware 5.6.x only supports PHP 7.4, which has it's active PHP support stopped November last year.
I would recommend when possible to plan upgrading Shopware to the latest 5.7.x release and upgrade the plugin along.

The upcoming Adyen plugin release will address further compatibility with the swagPaypal plugin, 
please note that these changes won't be made available for earlier versions of the plugin.

The files concerning the compatibility with SwagPayapl release in the current release 3.2.0:
Diff release 3.0.2..3.2.0: https://github.com/Adyen/adyen-shopware5/compare/3.0.2...3.2.0#files_bucket

* AdyenPayment\Shopware\Serializer\SwPaymentMeanSerializer
* AdyenPayment\Shopware\Serializer\SwPaymentMeanCollectionSerializer

These are used in the Subscriber/EnrichPaymentSubscriber.php 

These are the main changes for the compatibility, 
keep in mind that  current releases introduces new services which are not available in older versions.
