### ISSUE TITLE
Problem Bank Verification Visa

### ISSUE THREAD

**Issue by davymunch2203** [Adyen/adyen-shopware5#193]
Hi there,

When paying with visa, we encounter a problem when you have to verify with your bank. (you have to put in several codes to get a verification code)
Not all steps that you need to follow are shown. Only steps 1-3. Is the pop-up too short?
Because of this, we can't complete the payment

Problem occurred on Desktop with Chrome

**Comment by Suzell** [comment]
Has this been resolved yet? Thanks!

**Comment by olga-adyen** [comment]
Hi, I will close the issue due to inactivity. Pls contact the support partner though the support form form the "help section"
