### ISSUE TITLE
Restore custom attributes when the user adds wrong payment informations

### ISSUE THREAD

**Issue by isfett** [Adyen/adyen-shopware5#195]
**Describe the bug**
We have a custom field "configuration_id" in the mysql table s_order_details_attributes. This gets filled when the customer add a product to his cart. 

Everything is working when the customer cancels the payment (press the cancel button), comes back and do it again. The custom_attributes and the configuration_id are added as-well. I think that was handled by https://github.com/Adyen/adyen-shopware5/pull/159.

BUT the field is empty when the customer add wrong payment data (e.g. wrong credit card informations) and the payment fails. After a new payment our configuration_id (and other custom fields) are empty, so the fields are not restored like when the customer cancels his order on his own. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to checkout
2. Click on pay
3. Add wrong payment data (such as wrong credit card data) so the payment cancels in a way where the customer don't klick on cancel
4. See that custom field is not restored in s_order_details_attributes

**Expected behavior**
Custom fields are also restored on wrong payment information, not only on user canceling

**Screenshots**
-

**Server (please complete the following information):**
 - OS: Ubuntu

**Additional context**
Also an internal Ticket has been created by @ataberkylmz already. Maybe he could mention it.

**Comment by NilsVankan** [comment]
Wich version of the Adyen plugin are you using?

**Comment by isfett** [comment]
We are currently using 1.7.3

**Comment by NilsVankan** [comment]
> 

Hey,

Could you possible upgrade your version to the 3.2.0. version?
This problem is probably fixed in this version.
If you still encounter issues you can give us a sign.

Kind regards
