### ISSUE TITLE
Activating LIVE does not work

### ISSUE THREAD

**Issue by cyborgii** [Adyen/adyen-shopware5#196]
Hello,

As in the plugin UI configuration itself and in this class the environment is always in uppercase.
https://github.com/Adyen/adyen-shopware5/blob/46275f11a86c8e2b7fd1360a4d45052c4e427d21/Components/Configuration.php#L20
When using the strtolower with en excat match

The LIVE mode will never get activated.
https://github.com/Adyen/adyen-shopware5/blob/89dfbaa3110155439457037c0e8833e50d716f2c/Components/Configuration.php#L49

![Snag_71ab82ab](https://user-images.githubusercontent.com/247184/146529577-166341a0-90c8-49fa-bdcb-c0026e3ac381.png)
![Snag_71ab685d](https://user-images.githubusercontent.com/247184/146529563-17261477-18e1-4d4b-bd83-59d5b67aaa2e.png)

Regards,
Gregor Streng

**Comment by bortefi** [comment]
Dear Gregor Streng

This has addressed and updated in release 3.1.1 and release 3.2.0
Release-3.2.0 will made available be soon.
