### ISSUE TITLE
Shopware payment status not updating

### ISSUE THREAD

**Issue by TaiKamilla** [Adyen/adyen-shopware5#199]
After making and approved a payment (by Adyen) the payment status does not update in shopware

![image](https://user-images.githubusercontent.com/15035750/148214105-8977f236-4638-4a41-ab39-27bbb58f048a.png)
![image](https://user-images.githubusercontent.com/15035750/148214328-a22ce523-0656-4c19-9ae9-4f57cb851cb2.png)

I have set the webhooks and made sure that the webhooks work
![image](https://user-images.githubusercontent.com/15035750/148215490-41815970-e02f-4085-b4aa-10c54121db8d.png)

**Comment by NilsVankan** [comment]
Hey TaiKamilla,

which version of the Adyen plugin are you using?

Kind regards

**Comment by NilsVankan** [comment]
Hey @TaiKamilla,

we need more info about this, can you send us the TEST requests that you are doing because that "accepted" message you are getting is just from the "authorization" call and not for the request result itself.

Kind regards

**Comment by TaiKamilla** [comment]
> Hey TaiKamilla,
> 
> which version of the Adyen plugin are you using?
> 
> Kind regards

Hey @NilsVankan 
I am using Adyen 3.2 + Shopware 5.7.6

**Comment by TaiKamilla** [comment]
> Hey @TaiKamilla,
> 
> we need more info about this, can you send us the TEST requests that you are doing because that "accepted" message you are getting is just from the "authorization" call and not for the request result itself.
> 
> Kind regard

@NilsVankan 
The tests I did are the one in the Adyen panel under webhooks
![image](https://user-images.githubusercontent.com/15035750/151516652-28bdfbd1-6cdb-448d-97dc-f511d849ccfd.png)

**Comment by Suzell** [comment]
Hi Tai,

This is fixed now and we will release it in our next release planned for end of next week version 3.4.0. Thanks!

**Comment by NilsVankan** [comment]
Hi Tai,

regarding the issue it is not release related so sorry for the confusion.
We tested it and you should do the following steps to make it work:

1. Shopware cron installation:

[](https://docs.shopware.com/en/shopware-5-en/settings/system-cronjobs#examples-how-to-configure-the-cronjob)

This standard SW5 cron makes that the plugin cron does it's thing

2 Adyen webhooks, this is explained on Github from the plugin itself:
[](https://github.com/Adyen/adyen-shopware5/wiki#set-up-webhooks)

Kind regards

**Comment by TaiKamilla** [comment]
> Hi Tai,
> 
> regarding the issue it is not release related so sorry for the confusion. We tested it and you should do the following steps to make it work:
> 
> 1. Shopware cron installation:
> 
> [link](https://docs.shopware.com/en/shopware-5-en/settings/system-cronjobs#examples-how-to-configure-the-cronjob)
> 
> This standard SW5 cron makes that the plugin cron does it's thing
> 
> 2 Adyen webhooks, this is explained on Github from the plugin itself: [link](https://github.com/Adyen/adyen-shopware5/wiki#set-up-webhooks)
> 
> Kind regards

Ok, this did work, thanks!
But please add this to the documentation, cos is not documented anywhere
Thanks again!

**Comment by TaiKamilla** [comment]
> Hi Tai,
> 
> regarding the issue it is not release related so sorry for the confusion. We tested it and you should do the following steps to make it work:
> 
> 1. Shopware cron installation:
> 
> [link](https://docs.shopware.com/en/shopware-5-en/settings/system-cronjobs#examples-how-to-configure-the-cronjob)
> 
> This standard SW5 cron makes that the plugin cron does it's thing
> 
> 2 Adyen webhooks, this is explained on Github from the plugin itself: [link](https://github.com/Adyen/adyen-shopware5/wiki#set-up-webhooks)
> 
> Kind regards

@ NilsVankan, this did work, thanks!
But please add this to the documentation, cos is not documented anywhere
Thanks again!

**Comment by TaiKamilla** [comment]
> Hi Tai,
> 
> regarding the issue it is not release related so sorry for the confusion. We tested it and you should do the following steps to make it work:
> 
> 1. Shopware cron installation:
> 
> [link](https://docs.shopware.com/en/shopware-5-en/settings/system-cronjobs#examples-how-to-configure-the-cronjob)
> 
> This standard SW5 cron makes that the plugin cron does it's thing
> 
> 2 Adyen webhooks, this is explained on Github from the plugin itself: [link](https://github.com/Adyen/adyen-shopware5/wiki#set-up-webhooks)
> 
> Kind regards

@NilsVankan this did work, thanks!
But please add this to the documentation, cos is not documented anywhere
Thanks again!

**Comment by Suzell** [comment]
Thanks! We will add to docs!

**Comment by olga-adyen** [comment]
Task to add info to the docs has been added to the roadmap. This issue will be closed.
