### ISSUE TITLE
Don't create order if the payment fail

### ISSUE THREAD

**Issue by TaiKamilla** [Adyen/adyen-shopware5#205]
The order is created ever the payment is cancel/rejected/fail
And this ruins the statistics/conversions

Please don't create the order if the payment fails

![Screenshot 2022-02-23 at 18 45 33](https://user-images.githubusercontent.com/15035750/155377405-9f8b6c64-30bf-497c-be65-cf2b43595daa.png)
![Screenshot 2022-02-23 at 18 47 26](https://user-images.githubusercontent.com/15035750/155377424-ab79fab6-42e5-4a62-bf2e-2b566c2e7922.png)

**Comment by TaiKamilla** [comment]
This also ruins the google analytics convesions results

**Comment by Suzell** [comment]
Hi Tai, 

Actually we will always create an order before the payment. This is the best practice in case something happens and there is a payment with no order which could lead to many support questions and challenges finding the payment. 

The plugin relies on the offer closed notification to close any open orders when the payment expires. See more info on this here: https://github.com/Adyen/adyen-shopware5/wiki#manage-orders

**Comment by Suzell** [comment]
If this is not sufficient, happy to discuss new solutions to help make more accurate statistics with however keeping the order creation first. Therefore i will close this ticket now.
