### ISSUE TITLE
Additional description in the frontend

### ISSUE THREAD

**Issue by TaiKamilla** [Adyen/adyen-shopware5#207]
The additional description does not show in the frontend
This would be great to display a message to the customer about that payment method like a surcharge

<img width="928" alt="image" src="https://user-images.githubusercontent.com/15035750/163205631-3fde92bb-dddb-473b-9a99-a208dc132e5c.png">

**Something like this:**

![image](https://user-images.githubusercontent.com/15035750/163206283-af39c0b0-169b-4d0b-9759-e59ffb928bb1.png)

**Comment by olga-adyen** [comment]
Hi, thank you for your input, we have put it on our backlog.

**Comment by TaiKamilla** [comment]
Will this be fix, cos this looks like is a small bug

**Comment by olga-adyen** [comment]
Hey @TaiKamilla it's coming in the next release, going to be published this week.

**Comment by olga-adyen** [comment]
Closing, since it has been released.
