### ISSUE TITLE
Some order confirmation fail

### ISSUE THREAD

**Issue by TaiKamilla** [Adyen/adyen-shopware5#208]
Some customers are having issues with the orders/payment, and I say some cos most of them work fine
The customer set the payment details and tries to continue and it loads forever
But the order is created and the money transaction goes through, but since they have no confirmation (it just loads forever)
They try multiple times to create multiple orders and transactions, 
In the shopware logs, I get this
These are the attempts from the same customer
![image](https://user-images.githubusercontent.com/15035750/163353025-e202cafe-8dfb-4b40-a0fc-7a4b0e2a2f3a.png)

![image](https://user-images.githubusercontent.com/15035750/163352624-1e994e61-eeb8-4168-84ef-e2b620c3c5bc.png)
Any ideas?

**Comment by NilsVankan** [comment]
Hey Yafnar,

This seems to be a bug.
I made a ticket in the backlog and we will pick this up in one of the next releases.
i will give an update next week for the exact timeline.

kind regards

**Comment by olga-adyen** [comment]
Added to the plugin roadmap, can be closed.
