### ISSUE TITLE
Google Pay

### ISSUE THREAD

**Issue by andydandy80** [Adyen/adyen-shopware5#209]
Shopware: 5.7.7
Adyen-Plugin: 3.7.0

We trying to succesful implement Google Pay in our shop. For Google Pay it is necessary to register our website in Google Pay business console. But what is the correct url to enter there?
Our domain or the domain of adyen?
If we enter our url, no payment is possible, google error is "You have not registered to use this API".

But if you look at the call chain, it could be another url:
![Unbenannt](https://user-images.githubusercontent.com/45691258/165525867-4eb2e68e-2d50-4703-80d9-1a6a44df0ae5.png)

**Comment by DaveBueds** [comment]
Hi Andy,

Please check and follow the docs of google pay on this topic: https://developers.google.com/pay/api/web/guides/test-and-deploy/request-prod-access.
The correct url that you need to configure is the domain and or subdomains name of your webshop.

In the Adyen plugin you only have to configure the Google Merchant ID.

I hope this information helps you to further investigate the issue.

**Comment by davemeteor** [comment]
Hi Andy,

Please check and follow the docs of google pay on this topic: https://developers.google.com/pay/api/web/guides/test-and-deploy/request-prod-access.
The correct url that you need to configure is the domain and or subdomains name of your webshop.

In the Adyen plugin you only have to configure the Google Merchant ID.

I hope this information helps you to further investigate the issue.

**Comment by andydandy80** [comment]
Thanks for your reply. I think we have it so configured in google pay:

![image](https://user-images.githubusercontent.com/45691258/165693015-a2072011-d1e7-4f83-89a6-3dae0ce04b55.png)

But in checkout we are getting this notice:
![image](https://user-images.githubusercontent.com/45691258/165693161-819ed5c6-0a34-4ffb-acbf-9f95303f2067.png)

**Comment by andydandy80** [comment]
Problem is solved. In Adyen Customer Area "API Clientside Encryption Payments role" was missing and Google Pay was added twice in our account. Support solved the problem.
Perhaps interesting:
https://docs.adyen.com/payment-methods/google-pay/web-component#test-and-go-live
