### ISSUE TITLE
Option required for order status

### ISSUE THREAD

**Issue by magnolia4** [Adyen/adyen-shopware5#219]
Since the order is created in Shopware before adyen capturing, we need an option for the order status on the plugin to be able to set the status if the order has the payment status "the_process_has_been_cancelled". Currently, this always remains at "open".

**Comment by adyen-integrations-support** [comment]
Hello,

Thanks for submitting that thoughtful idea the product team is excited to review it and process it further.
We will keep you posted about the status of this change request.

We appreciate your recommendation.

Thank you,
Best regards.

**Comment by magnolia4** [comment]
Hello Olga,

what does the status "closed" mean?
Was the ticket closed because it will be released with the upcoming version or because it will not be implemented?
