### ISSUE TITLE
What does the option "delayed" mean?

### ISSUE THREAD

**Issue by magnolia4** [Adyen/adyen-shopware5#233]
When is payment captured with the “delayed” option?

![image](https://github.com/Adyen/adyen-shopware5/assets/9446008/476a995c-bde0-4979-9b45-ce4ebd27d6e8)

**Comment by logeecom** [comment]
Hello @magnolia4 

Delayed capture happens automatically after a defined period of time after the payment is made.
When you choose the delayed option you will have to define how many days after authorization you want the payment to be captured in other words the delay between the authorization and scheduled auto-capture, specified in hours. You will enter a number from 1 to 7. Number 1 means 24 hours. 

![Delayed capture](https://github.com/Adyen/adyen-shopware5/assets/20204230/f1c50fb6-1179-4720-8e20-15cc78fd4d61)


Best regards.
