### ISSUE TITLE
[PW-2636] Handle duplicated notifications

### ISSUE THREAD

**Issue by cyattilakiss** [Adyen/adyen-shopware5#28]
**Describe the bug**
It can happen that the same notifications are sent multiple times. In case of notification duplication.
Example which fields you need to check to identify duplicated notifications:
https://github.com/Adyen/adyen-magento2/blob/6.4.0/Controller/Process/Json.php#L373-L379

When a duplicate notification is being received it can be ignored and not stored.

**To Reproduce**
1. Send a notification 2 times to the shopware plugin.

**Expected behavior**
In case duplicated notifications are sent the plugin only accepts 1

**Comment by olga-adyen** [comment]
Solved in the last release.
