### ISSUE TITLE
[PW-2570] Do refunds based on original PSP reference instead of notifications PSP reference

### ISSUE THREAD

**Issue by acampos1916** [Adyen/adyen-shopware5#29]
**Describe the bug**
There can be common edge cases when this fails. Let's take an iDeal payment as an example:
You start the payment, an offer is created, go back and open the app again, a new offer is created, as soon as you finish the payment the first offer is cancelled and an offer_closed notification is sent with X psp reference. For the payment you get an Authorisation notification with Y psp reference. If you are not lucky then the offer_closed notification is going to be the "last" notification for the order and then the psp reference won't match therefore the refund cannot be done.

**To Reproduce**
1. You start the payment, an offer is created.
2. Go back and open the app again, a new offer is created, as soon as you finish the payment the first offer is cancelled and an offer_closed notification  is sent with X psp reference.
3. For the payment you get an Authorisation notification with Y psp reference. 

**Expected behavior**
It would be better to store the original pspreference for the order when the async notification from our server or the sync authorisation response from the API is processed.

**Comment by cyattilakiss** [comment]
Duplicate: https://github.com/Adyen/adyen-shopware5/issues/17
