### ISSUE TITLE
[PW-2746] Verify that the cookies are registered as technical/required

### ISSUE THREAD

**Issue by cyattilakiss** [Adyen/adyen-shopware5#30]
**Describe the task**
Shopware requested us to verify if the cookies are requested as technical/required. 

**Steps**
1.  Search for the cookie key in the code
2. Check the group to which the cookie is assigned
3. Verify in the frontend if the cookie is listed in the technical group

**Comment by wannevancamp** [comment]
Since version 5.6.3 the plugin registers technical cookies via the Shopware Cookie consent manager. This is already verified by a technical review of Shopware.
