### ISSUE TITLE
Error after cancelation an order

### ISSUE THREAD

**Issue by jensorben** [Adyen/adyen-shopware5#32]
**Describe the bug:**
After finishing an order we want to cancel the payment process e.g. Sofort. 
After that, System got an Fatal error in the Adyen Plugin, telling us, the OrderNumber has to be integer. But all order numbers in shopware are strings? 

**To Reproduce:**
Put something into basket
Go to checkout
Select a payment method (not CreditCard)
Send order
Cancel payment method

**Expected behavior:**
Open the Checkout page or Homepage

![Adyen](https://user-images.githubusercontent.com/69344793/89645303-c9897680-d8b9-11ea-9df0-f40e6afa545f.png)

**Comment by jensvandorpe** [comment]
@jensorben which version of Shopware are you using? Which version of the plugin are you using?

**Comment by jensorben** [comment]
@jensvandorpe We're on Shopware Version 5.6.7
At the time, the issue was created we were on plugin version 1.4.1 I guess. 
At the moment we're on plugin version 1.7.0 and the error still exists!

See also : https://www.adyen.help/hc/en-us/requests/1845991

**Comment by jensorben** [comment]
@jensvandorpe Issue solved with Version 1.7.2!

Thx
