### ISSUE TITLE
[PW-2979] Support for Adyen's 3DS fallback policy

### ISSUE THREAD

**Issue by acampos1916** [Adyen/adyen-shopware5#50]
**Is your feature request related to a problem? Please describe.**
The redirectShopper after 3DS fallback policy is not yet taken into consideration by this plugin.

**Describe the solution you'd like**
The flow would be as follows: /payments ==> identifyShopper (3DS2 native resultCode) ==> /payments/details ==> redirectShopper (3DS1 resultCode) ==> /payments/details

**Additional context**
Test data to trigger the fallback:
Enable ADP threeDSFallBackPolicy in Adyen's CA
Card: 4917610000000000
cvc: 737
expiryMonth: 10
expiryYear: 2020
order amount: 120.03 EUR

**Comment by wannevancamp** [comment]
@acampos1916 , the returnUrl for the 3D Secure 1 fallback is already included in the payment request. Can you explain what we need to implement? Is there some documentation available for the 3DS fallback policy?

Thanks

**Comment by acampos1916** [comment]
Hello @wannevancamp,

Using the data to trigger the fallback you'll see the following:

- The `/payments` call will return `IdentifyShopper`, when the plugin handles this a `/payments/details` call is triggered.
- This will return a `RedirectShopper`, and once that's handled then another `/payments/details`.
- That last call is returning an error from the Adyen API `Missing payment method details`.

I see that the last `/payments/details` call is correctly formatted but maybe the PaRes and MD are not the correct ones. I hope this has made the issue clearer, let me know if you need further info.

**Comment by bortefi** [comment]
Hi @acampos1916 Could you verify if this issue still exists on the current develop branch?
The code base related to 3DS has been updated in previous tickets.
