### ISSUE TITLE
Cronjobs are not running

### ISSUE THREAD

**Issue by EggersS1** [Adyen/adyen-shopware5#54]
**Describe the bug**
Recurring payments are not going out from the AboCommerce (Shopware 5) to Adyen to support subscription payments.

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function AdyenPayment\Components\NotificationProcessor\Authorisation::__construct(), 3 passed in /var/customers/webs/draeger/ppe-shop/var/cache/production_202005221140/proxies/ShopwareProduction3362b35eaa965cff4f4fccda9aa2ef9f3ec56040ProjectContainer.php on line 6526 and exactly 4 expected in /var/customers/webs/draeger/ppe-shop/custom/plugins/AdyenPayment/Components/NotificationProcessor/Authorisation.php:49
Stack trace:
#0 /var/customers/webs/draeger/ppe-shop/var/cache/production_202005221140/proxies/ShopwareProduction3362b35eaa965cff4f4fccda9aa2ef9f3ec56040ProjectContainer.php(6526): AdyenPayment\Components\NotificationProcessor\Authorisation->__construct()
#1 /var/customers/webs/draeger/ppe-shop/vendor/symfony/dependency-injection/Container.php(306): ShopwareProduction3362b35eaa965cff4f4fccda9aa2ef9f3ec56040ProjectContainer->getAdyenPayment_Components_NotificationProcessor_AuthorisationService()
#2 /var/customers/webs/draeger/ppe-shop/engine/Shopware/Compo in /var/customers/webs/draeger/ppe-shop/custom/plugins/AdyenPayment/Components/NotificationProcessor/Authorisation.php on line 49

**To Reproduce**
1. Adyen plug in approved in Shopware 5 backend
2. Cronjub is runnning 
3. Payment trigger isn't sent to Adyen

**Expected behavior**
Subscription payments are able to process via digital payment provider

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari, mozilla]

**Additional context**

**Comment by Byorun** [comment]
The component.xml is missing the new 4th parameter [https://github.com/Adyen/adyen-shopware5/blob/develop/Resources/services/components.xml](url)

**Comment by EggersS1** [comment]
Hi Byorun, many thanks for the reply. we are using the standard plug in from adyen. Has adyen to change it in the plug in or is supposed to change something?

**Comment by Byorun** [comment]
@EggersS1 This is a bug in the current version of the plugin, we already notified adyen about it, my guess is that we will soon see a 1.5.1 hotfix.

If you can't wait for a fix you can add
`<argument type="service" id="models"/>`
as the 4th argument parameter for the service registration in `Resources/services/component.xml` for adyen_payment.components.notification_processor.authorisation and adyen_payment.components.notification_processor.capture

**Comment by EggersS1** [comment]
Hi acampos1916, does it mean that cronjobs now are possible to make? and that it support subscritpion models?

**Comment by EggersS1** [comment]
Greate to see is there already a date published when the release with bug fixes will be available?

**Comment by cyattilakiss** [comment]
> Greate to see is there already a date published when the release with bug fixes will be available?

Hi @EggersS1 ,
@acampos1916 is working on the release at the moment, hopefully it will be published today 👍 
Best,
Attila
Adyen
