### ISSUE TITLE
Handle tokenisation (OneClick and Recurring)

### ISSUE THREAD

**Issue by floorjubbega** [Adyen/adyen-shopware5#60]
This is a feature request for tokenising payments, which would allow the use of OneClick and Recurring transactions.

The payments would need to be tokenised when calling the /payments endpoint, where the storePaymentMethod field is set to true. The checkout component state.data can be used for local payment methods. A new config field would need to be implemented to allow for a "checkbox" providing the shopper with a choice to store their payment details. When that feature is enabled, the plugin should set the field to true. It also should indicate what kind of transaction the payment is e.g "shopperInteraction": "Ecommerce".

When making a OneClick, MOTO or subscription payment [the fields from the docs](https://docs.adyen.com/checkout/tokenization/create-and-use-tokens#set-parameters-to-flag-transactions) need to be provided.

Related documentation: 
- [Tokenization](https://docs.adyen.com/checkout/tokenization)
- [Storing of OneClick tokens](https://docs.adyen.com/checkout/tokenization/create-and-use-tokens#save-for-one-off)
- [Storing of Recurring tokens](https://docs.adyen.com/checkout/tokenization/create-and-use-tokens?tab=subscriptions_2#save-for-subscriptions)
- [API explorer](https://docs.adyen.com/api-explorer/#/Recurring/v49/overview)

**Comment by Akono1212** [comment]
The function is very important to our business. Please implement as soon as possible.

**Comment by KR2109** [comment]
We would also need this feature. We ask for realization.

**Comment by magnolia4** [comment]
For our customer we urgently need the compatibility with plugin from Shopware "Subscriptions" (https://store.shopware.com/en/swagabocommerce/subscriptions-commerce.html)

**Comment by bekteshik** [comment]
This feature would be very helpful for our business and would enhance our customers' experience. We hope to see this released.
