### ISSUE TITLE
Amazon Pay

### ISSUE THREAD

**Issue by acampos1916** [Adyen/adyen-shopware5#65]
**Depends on #62, #61**
**Please wait with it until the component is ready - we are going to update this issue**

Instructions to implement Amazon Pay payment method: https://docs.adyen.com/payment-methods/amazon-pay

**Comment by Suzell** [comment]
web component ready https://docs.adyen.com/payment-methods/amazon-pay/web-component

**Comment by olga-adyen** [comment]
Added to roadmap, will close.
