### ISSUE TITLE
Compatibility with Shopware 5.2

### ISSUE THREAD

**Issue by acampos1916** [Adyen/adyen-shopware5#67]
Is the plugin fully compatible with Shopware 5.2? How to declare the cookies without the Cookie Consent Manager?

**Comment by wannevancamp** [comment]
The plugin is currently compatible with version 5.3.7 and above. I do not recommend making the plugin compatible with 5.2. There are a lot of breaking changes between 5.2 and 5.3. Also the plugin system is totally different between those versions.

As of Shopware 5.6.3, the Cookie Consent Tool is included in the Shopware core as a standard function. Version lower then 5.6.3 the Cookie Consent Tool needs to be installed.
Github repository: https://github.com/shopwareLabs/SwagCookieConsentManager

**Comment by Suzell** [comment]
@wannevancamp we have a merchant enquiring about the compatibility with Shopware v5.6.9. Can you check this please?

**Comment by wannevancamp** [comment]
@Suzell , the plugin is tested on 5.6.8. 
The latest Shopware version 5.6.9 is a security update and should be compatible with the current version (1.5.1) of the plugin.
