### ISSUE TITLE
[PW-3357] Notification URL too generic / error with other plugins

### ISSUE THREAD

**Issue by oleohlen** [Adyen/adyen-shopware5#73]
The URL notification URL for status transmission is too generic. Various shopware extensions also use this URL. This leads to errors and to the fact that orders / transactions are not marked as paid. 

The currently used URL is: /frontend/notification/index
Better would be a specific one for Adyen. For example..: 
/frontend/notification/index/adyen

**Comment by acampos1916** [comment]
Hello @oleohlen, thanks for opening this issue.

We've moved this to our backlog.

Cheers,
Ángel
