### ISSUE TITLE
Plugin Errors

### ISSUE THREAD

**Issue by danielDigitalArt** [Adyen/adyen-shopware5#8]
I pulled directly from github but am unable to get the plugin running, i also checked out the development and 1.4.1 Branch, none worked so far in Shopware 5.6.6, i can not open the Backend or the Frontend of the Shop. The First Error i encountered was:
`Fatal error: Uncaught Error: Class 'MeteorAdyen\Components\CompilerPass\NotificationProcessorCompilerPass' not found in /path/to/hosting/httpdocs/custom/plugins/MeteorAdyen/MeteorAdyen.php:59`
I opened the File "Components/ShopwareVersionCheck.php", there i found that the wrong Namespace is used, it writes "AdyenPayment" instead of "MeteorAdyen". 

I changed that but get another Error:
`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "meteor_adyen.components.shopware_version_check". in /path/to/hosting/httpdocs/vendor/symfony/dependency-injection/ContainerBuilder.php:1060`
so i also checked the File at "Components/CompilerPass/NotificationProcessorCompilerPass.php" which also has the wrong Namespace, when i changed that the Error still persisted, so i could not find a way to get the Plugin working.

**Comment by acampos1916** [comment]
Hello @danielDigitalArt,

MeteorAdyen used to be the namespace previous to the official release of this plugin, if you're replacing that extension with this plugin make sure that the old directory is completely replaced by AdyenPayment.

Thanks,
Ángel Campos

**Comment by danielDigitalArt** [comment]
Thank you, it worked.

**Comment by danielDigitalArt** [comment]
Currently i have another Problem, i can not save the Plugin configuration, i already uninstalled and reinstalled the Plugin, tried different branches and also removed all possible configuration inside the database i could find, bc it could be an interference by the old plugin. still had no luck to sav any settings for this plugin. Any ideas?

**Comment by acampos1916** [comment]
@danielDigitalArt sounds like your plugin is missing the required dependencies. Try running `composer install --no-dev` in the `AdyenPayment` directory.

I checked our documentation and noticed that this installation step was missing, thank you!

**Comment by danielDigitalArt** [comment]
@acampos1916 i tried this now and composer installed some dependencies, yet still no luck for adding some configuration, i can see the configs in the plugin manager but it is not able to save them. When i go into the Basic Settings of Shopware and then to the Plugin Area where the Config can also be changed i see no fields:
![Bildschirmfoto 2020-06-19 um 12 49 22](https://user-images.githubusercontent.com/25100967/85125302-a3394a00-b22b-11ea-9fb1-04e376afe04e.png)

**Comment by acampos1916** [comment]
Hello @danielDigitalArt,

Thanks for the info, we haven’t been able to reproduce that problem though. I see in your screenshot 'Shopware Plugin by Meteor' which means that there's still some confusion in your system regarding the old and new plugin and that could be the issue.

If you already replaced the old directory with the new one completely then I would suggest reinstalling the AdyenPayment plugin and making sure that the cache has been cleared. If the problem persists you can try installing the plugin in a fresh Shopware 5 instance so you're able to troubleshoot further.

Keep us updated!
Ángel

**Comment by danielDigitalArt** [comment]
Hello @acampos1916,
i can confirm that when i install the plugin into a shop system that did not have the old plugin installed, the plugin configuration works. Now i dont know how to solve the problem, because it woul mean that the shop would have to be build from ground up. I also tried to uninstall and remove the old plugin before installing this version, still it did not work. Any ideas, what could cause this?

**Comment by acampos1916** [comment]
Hey @danielDigitalArt,

Sorry to hear that you're still having issues. I just tried installing the previous version of the plugin, setting a configuration, and replacing the plugin with the new version as to try to reproduce it and did not face the problem you're having. I was able to save and test the configuration successfully both times. I would recommend to check the Shopware and webserver logs to find errors that could be silently breaking your instance and let us know if there are lines related to the plugin.

Even after uninstalling the old plugin and installing the new version do you still get the message shown [here](https://github.com/Adyen/adyen-shopware5/issues/8#issuecomment-646571071)? If so I believe this could be a cache issue, you can try searching your filesystem and database for those strings and see where it pops up.

Cheers,
Ángel

**Comment by danielDigitalArt** [comment]
Hey @acampos1916 ,

i could find what is causing this problem. The Main Shop had the position "3" and a language Shop had the position "1" thus in the configuration of the plugin this order is applied an the first tab is the Language Shop. When you try to hit save, the plugin will check if the required fields are filled out if not it refuses to save (without a message). When you switch to the tab of the main shop then you will see that these fields are marked as required/underlined. ITs a bit weird that the System also does not mark the fields of the language shop as required.

**Comment by acampos1916** [comment]
@danielDigitalArt good to hear you sorted it out!

So the required fields were highlighted for the default shop and since this wasn't the first tab you didn't see the Save was failing. Let us know if you think this is a Shopware 5 matter or a shortcoming of the plugin.

Ángel

**Comment by danielDigitalArt** [comment]
@acampos1916 i think that is a bug within Shopware, although i could not test it on a different plugin right now.
