### ISSUE TITLE
Add Paypal Redirect

### ISSUE THREAD

**Issue by Suzell** [Adyen/adyen-shopware5#80]
Add Paypal into the list of supported redirect payment methods. This is a simple redirect payment method and no component needs to be rendered. 

Build the request 'paymentMethod' object for PayPal. Here is an example: https://docs.adyen.com/api-explorer/#/CheckoutService/v65/post/payments__example_payments-giropay

To test you need to have a PayPal dev account. https://developer.paypal.com/developer/accounts/

**Comment by acampos1916** [comment]
Paypal is already supported with a RedirectShopper flow.
