### ISSUE TITLE
[PW-3575] Notifications sent to more than one endpoint

### ISSUE THREAD

**Issue by jensorben** [Adyen/adyen-shopware5#81]
We have a notification endpoint setup for Shopware and a second endpoint for our own ERP System. 
Creating orders directly from our ERP is also initiating notifications to the shopware endpoint. This should be ignored by the endpoint, but are currently being responded to with:

{
   "intoCountryCode" : "NL",
   "[notification save error]" : null
}

Additionally: Troubleshooting at Adyen Backend and manual acception wouldn't help. It seems that notifications were sent more than one time!

**Comment by bortefi** [comment]
@jensorben 

If I understand the question correctly 
1. an ERP systems sends a payment call to Adyen 
2. Adyen is configured to call 2 separate notification endpoints
3. Adyen sends notifications to both the Shopware instance as the ERP System

@acampos1916 
I would expect this to be normal behaviour, as Adyen would notify all notification endpoints.
Is there a way to differentiate who the actual sender was of the payment call related to the sent notifications?

**Comment by acampos1916** [comment]
Hello @jensorben, @bortefi,

Indeed sounds like normal behaviour, Adyen will send notifications to every Server Communication endpoint configured for that merchant account.

But manually accepting the notifications shouldn't be necessary, if the plugin is responding with that `intoCountryCode ...` message then I can see why you would have to troubleshoot in the Customer Area.

Ideally the plugin would authenticate the request and respond with `[accepted]` ([Docs](https://docs.adyen.com/development-resources/webhooks#accept-notifications)). And then if the cronjob is not able to find the order in Shopware the notification would be ignored, assuming that the ERP and Shopware order numbers have different sequences.

Cheers,
Ángel

**Comment by jensorben** [comment]
@bortefi 
You're right. Additionally Adyen backend sends billing information notifications which neither ERP nor Shopwareplugin can handle.

@acampos1916 
Notification will be ignored by shopware, that's right. But adyen will queue that notification as long as it will be accepted. And so the notification channel will be blocked by them. e.g. last week on Monday we have three open orders in shopware placed during the weekend, although we have a settled iDEAL payment on adyen backend. After I "cleaned up" the notification channel by manually accepting them, these iDEAL-orders were set to "complete payment" only a couple of seconds later.

So in my opinion you have to channel the notifications to the belonging sender as @acampos1916 asked or stop queuing them after a couple failed retries.

Best
Jens

**Comment by acampos1916** [comment]
Thanks @jensorben. I checked and you're right, if the order to which the notification belongs doesn't exist in Shopware then the endpoint won't respond with `[accepted]` and the notification queue must be cleared manually to get newer notifications. I've created an internal ticket to work on this.

**Comment by cyattilakiss** [comment]
@acampos1916 has this issue been fixed in the #114 ?

**Comment by acampos1916** [comment]
@cyattilakiss yes, I see the link was not created. Closed now.
