### ISSUE TITLE
adyen.js Error on German language shop

### ISSUE THREAD

**Issue by jensorben** [Adyen/adyen-shopware5#84]
We set up adyen plugin to our developer shop it works fine. Our Mainshop is english and we have a couple of language shops for european customers. 
At the end of october suddenly the adyen.js Version 3.8.1. starts throwing errors on german language shop as shown (Screenshot attached). Re-installing didn't solve the problem. 
After a clean install and set up Adyen for the Live-Shop we got the same issue.

We solved the problem temporarily by swithcing the plugin to adyen.js Version 3.9.5. instead.
![Screenshot 2020-10-29 170623](https://user-images.githubusercontent.com/69344793/99268668-c5a8b100-2825-11eb-8a94-585b61767b88.jpg)

**Comment by rdlgroup** [comment]
We have the exact same problem with Shopware 5.6.6 and latest Adyen Plugin. 

![image](https://user-images.githubusercontent.com/75075991/100348233-ee2f6880-2fe6-11eb-8da6-b35ad892ae6b.png)

**Comment by acampos1916** [comment]
Hello @jensorben @rdlgroup,

Could you check if upgrading the Adyen Web Components to 3.12.1 solves this issue for you? We've merged #96 with that upgrade.

**Comment by jensorben** [comment]
Hello Àngel,

should we test this it on the Adyen Plugin Version 1.5.1 or on the new Vesion 1.6.0?

Best

Jens

Von: Ángel Campos <notifications@github.com>
Gesendet: Montag, 7. Dezember 2020 13:45
An: Adyen/adyen-shopware5 <adyen-shopware5@noreply.github.com>
Cc: Jens Orben <jorben@energetix.tv>; Mention <mention@noreply.github.com>
Betreff: Re: [Adyen/adyen-shopware5] adyen.js Error on German language shop (#84)


Hello @jensorben<https://github.com/jensorben> @rdlgroup<https://github.com/rdlgroup>,

Could you check if upgrading the Adyen Web Components to 3.12.1 solves this issue for you? We've merged #96<https://github.com/Adyen/adyen-shopware5/pull/96> with that upgrade.

**Comment by acampos1916** [comment]
@jensorben version 1.6.0 solves some bugs with redirect payment methods, so better to use that one.

**Comment by rdlgroup** [comment]
Hello Angel,

We updated the plugin based on the Github link. It looks like Klarna 
works but credit card fields cannot be filled in (checked with the 
responsive theme too) and Sofort redirect doesn't work.

Best regards,
Satenik
Am 08.12.2020 um 08:49 schrieb jensorben:

**Comment by acampos1916** [comment]
Hello @rdlgroup, we're not aware of an issue affecting CC fields, is there an error in the console or logs that could indicate what is the problem?
