### ISSUE TITLE
Unfinished orders

### ISSUE THREAD

**Issue by jensorben** [Adyen/adyen-shopware5#85]
We have a couple of orders on our shop which wern't finished finally. We investigated most issues were caused because the plugin redirects to the **confirm** page of shopware instead of targeting the **finish** page, which is called normally.
At the adyen backend we see these orders at the Offers-Section being kept as **Open** for 12 hours before it was cancelled by system. 

Additional informations: 
Problem only occurs on payment method **credit card**
Most of these "broken orders" are coming from customers using the french language shop!
From one customer we got feedback, that her browser crashed with error report: _The page shop.energetix.tv was closed unexpectedly!_

**Comment by msilvagarcia** [comment]
Hey @jensorben !

Thanks for reporting it, and sorry we didn't report it before. At the time we were still working in a pre-release version.

If you update to the latest version of the plugin, do you still face the issue?

Kind regards,
Marcos
Adyen

**Comment by wannevancamp** [comment]
@msilvagarcia , @acampos1916 , this issue is related to #106

**Comment by jensorben** [comment]
Hi @msilvagarcia,
after installing the new version we didn't hear anything more. 

Best

Jens
