### ISSUE TITLE
IE compatibility: plugin blocks page loading 

### ISSUE THREAD

**Issue by wannevancamp** [Adyen/adyen-shopware5#97]
**Describe the bug**
Since 1.6.0 the plugin is not compatible with IE 10 and lower. The compiled JS blocks loading every page.

**To Reproduce**
1. Go to IE 10 or lower
2. Open a page
3. Page not loading because of several JS errors

**Expected behavior**
All pages loading

**Comment by wannevancamp** [comment]
@msilvagarcia , @acampos1916 : this one is blokking for all users on IE, this because the whole site stops loading. Because of that, it's not suggested to use release 1.6.0

**Comment by acampos1916** [comment]
Hello @wannevancamp,

IE10 is currently not supported by the component. I'll be closing this issue but let us know if there are any other insights.

**Comment by jensvandorpe** [comment]
@acampos1916 can you confirm IE 11 is supported by the component?
