### ISSUE TITLE
Payconiq logo

### ISSUE THREAD

**Issue by Euroshoe** [Adyen/adyen-shopware5#99]
The current logo used for Payconiq by bancontact is the same as bancontact itself.
This causes confusion for customers (even though the title explains the differences between the 2 payment methods)
In order to get this fixed, the logo should be updated to the correct one.

**Comment by wannevancamp** [comment]
@acampos1916 , this can be closes since 3.0.0 because payment logo's are configurable for each payment method. Thx!
